name: test
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        zig-version: ['0.14.1']

    runs-on: ubuntu-latest
    name: Run tests on Zig ${{ matrix.zig-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}
      - run: zig fmt --check ./*.zig src/*.zig
      - run: zig build test
